pull: true
ignore: 3
debounce: 2
server:
  host: 127.0.0.1
  port: 2222
user:
  username: admin
  password: admin123
repos:
 - name: test
   path: test/git
   url: https://github.com/example/example.git
   branch: master
   username: user
   password: 123456
   email: user@example.com
   pull: true
   ignore: 3
   debounce: 2
   